### PR TITLE
Mbio eda uses eda-sepcific faq page

### PR DESCRIPTION
**Pull request by asizemore**
With StaticContent PR, resolves https://github.com/VEuPathDB/StaticContent/issues/20

This PR updates the faq route based on if the site is using the eda.

### CODE REVIEW

**Comment by asizemore** [comment]
Hey @jtlong3rd ! This is my first adventure into modifying any of the static content so at this stage i'm just hoping to ensure I know all the pieces and parts at this stage!

So the `index.js` will render `faq_beta.html` which is generated from the markdown file [here](https://github.com/VEuPathDB/StaticContent/pull/21/files), which in turn uses the yml file also in that PR. Somewhere (couldn't find where) the full file name gets split and put into a MicrobiomeDB folder and named with whatever comes after MicrobiomeDB ... so `MicrobiomeDB_faq_beta.md` will become `static-content/MicrobiomeDB/faq_beta.html`, correct?

**Review by jtlong3rd — APPROVED** [review]
Should be good to merge when you're done with the [associated Static Content PR](https://github.com/VEuPathDB/StaticContent/pull/21)!

**Comment by jtlong3rd** [comment]
> Hey @jtlong3rd ! This is my first adventure into modifying any of the static content so at this stage i'm just hoping to ensure I know all the pieces and parts at this stage!
> 
> So the `index.js` will render `faq_beta.html` which is generated from the markdown file [here](https://github.com/VEuPathDB/StaticContent/pull/21/files), which in turn uses the yml file also in that PR. Somewhere (couldn't find where) the full file name gets split and put into a MicrobiomeDB folder and named with whatever comes after MicrobiomeDB ... so `MicrobiomeDB_faq_beta.md` will become `static-content/MicrobiomeDB/faq_beta.html`, correct?

Sounds about right!

**Comment by jtlong3rd** [comment]
> Hey @jtlong3rd ! This is my first adventure into modifying any of the static content so at this stage i'm just hoping to ensure I know all the pieces and parts at this stage!
> 
> So the `index.js` will render `faq_beta.html` which is generated from the markdown file [here](https://github.com/VEuPathDB/StaticContent/pull/21/files), which in turn uses the yml file also in that PR. Somewhere (couldn't find where) the full file name gets split and put into a MicrobiomeDB folder and named with whatever comes after MicrobiomeDB ... so `MicrobiomeDB_faq_beta.md` will become `static-content/MicrobiomeDB/faq_beta.html`, correct?

Some extra detail:

1. The actual url to the FAQ will be `{COMMUNITY_SITE}/MicrobiomeDB/faq_beta.html` (e.g., `https://qa.static-content.veupathdb.org/MicrobiomeDB/faq_beta.html` on QA sites). The `COMMUNITY_SITE` is set in conifer.
2. The client defines a special [/static-content](https://github.com/VEuPathDB/EbrcWebsiteCommon/blob/3977e4f1bbacbcabe7107756072b5ef5834c29aa/Client/src/routes.jsx#L106-L112) route which will issue a request (a "redirect" of sorts) to whatever `COMMUNITY_SITE` was configured

**Comment by asizemore** [comment]
ahhhhhhh so cool! Thank you for the review and the extra details!!

**Pull request merged**
