### PR TITLE
feature: add Go button to differential abundance app

### PR DESCRIPTION
**Pull request by asizemore**
This PR involves the addition of a "Go" button to the differential abundance app. 

In order to complete this feature, we needed to restructure the `server.R` file. The relevant parts of the proposed new structure are as follows:

```
mainChart <- renderUI(

  generatePlot()

)

generatePlot <- reactive(

    ...validate inputs...
    ...prepare data for DESeq...
    
      runDeseq()

    ...generate plot if DESeq successful...

)

runDeseq <- eventReactive(
    ...run DESeq...
)
```

*Notes:* 
- The above deviates from our original plan for a chain of reactives because calling, for example, a reactive `validateInputs` function within `generatePlot` or `runDeseq` will not necessarily be run on the button click (which runs `runDeseq`). Since the `validateInputs` function would have to isolate the input variables, it does not have any dependencies that would be updating so does not run. If we definitely wanted a `validateInputs` function, one idea would be to force it to run by making it depend on `input$go`. 
- There is still one ui bug -- the "Running DESeq2..." message displays on top of the the loading spinner gif. In progress.
- Still need to verify we have all the original input checks. In progress.
- We might also want to rename the button. Perhaps "Run analysis", "Run DESeq2", "Generate plot", or something similar?

### CODE REVIEW

**Comment by d-callan** [comment]
Why would the inputs need isolating within the validateInputs reactive?

**Comment by asizemore** [comment]
Aha! Indeed the inputs did _not_ need isolating - you're right. With the latest commit I added the validateInputs function in addition to a data prepping function (just to make the code cleaner).

**Review by d-callan — APPROVED** [review]
i find the prepForDeseq reactive a bit curious. if the only input it depends on is taxon level, then it basically serves as a cache for the data at the specified level. fine. but it seems there are a number of intermediary tables that are scoped outside the reactive and saved to the server function. are all of these used? or is it possible we could just return a single result, or list of two perhaps? and then use the returned result?

**Comment by asizemore** [comment]
This PR also now includes 1) a fix that allows the data table to render and 2) a fix for the case when "Not Factor 1" includes NAs.

**Pull request merged**
